In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\BHUPESH\Desktop\Laptop_project\laptopPrice_cleaned.csv')

In [3]:
df

,brand,processor_brand,processor,gen,ram,ssd,hdd,os,os_bit,gpu,warranty,Touchscreen,msoffice,rating,Price,Number of Ratings,Number of Reviews
0,1,1,1,0,4,0,1024,2,1,0,3,0,0,2,34649,3,0
1,5,1,1,0,4,0,1024,2,1,0,3,0,0,3,38999,65,5
2,5,1,1,0,4,0,1024,2,1,0,3,0,0,3,39999,8,1
3,1,1,2,0,8,512,0,2,0,1,3,0,0,3,69990,0,0
4,1,1,0,7,4,0,512,2,1,0,3,0,0,3,26990,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
797,1,0,10,7,4,1024,0,2,1,0,0,0,0,3,135990,0,0
798,1,0,10,7,4,1024,0,2,1,0,0,0,0,3,144990,0,0
799,1,0,10,7,4,1024,0,2,1,2,0,0,0,3,149990,0,0
800,1,0,10,7,4,1024,0,2,1,2,0,0,0,3,142990,0,0
801,5,0,8,0,8,512,0,0,1,0,3,0,0,4,57490,18,4

In [4]:
df.dropna(inplace=True)
x = df.drop('Price',axis=1)
y= df[['Price']]

In [5]:
x

,brand,processor_brand,processor,gen,ram,ssd,hdd,os,os_bit,gpu,warranty,Touchscreen,msoffice,rating,Number of Ratings,Number of Reviews
0,1,1,1,0,4,0,1024,2,1,0,3,0,0,2,3,0
1,5,1,1,0,4,0,1024,2,1,0,3,0,0,3,65,5
2,5,1,1,0,4,0,1024,2,1,0,3,0,0,3,8,1
3,1,1,2,0,8,512,0,2,0,1,3,0,0,3,0,0
4,1,1,0,7,4,0,512,2,1,0,3,0,0,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
797,1,0,10,7,4,1024,0,2,1,0,0,0,0,3,0,0
798,1,0,10,7,4,1024,0,2,1,0,0,0,0,3,0,0
799,1,0,10,7,4,1024,0,2,1,2,0,0,0,3,0,0
800,1,0,10,7,4,1024,0,2,1,2,0,0,0,3,0,0
801,5,0,8,0,8,512,0,0,1,0,3,0,0,4,18,4

In [6]:
y

      Price
0     34649
1     38999
2     39999
3     69990
4     26990
..      ...
797  135990
798  144990
799  149990
800  142990
801   57490

[802 rows x 1 columns]

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [8]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((641, 16), (161, 16), (641, 1), (161, 1))

In [9]:
from sklearn.linear_model import LinearRegression 
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [10]:
lr.score(x_train, y_train)

0.704368866738694

In [11]:
lr.score(x_test, y_test)

0.6450591624677684

In [12]:
pred = lr.predict(x_test)

In [13]:
pred = pd.DataFrame(pred )

In [14]:
pred

                 0
0     41735.055379
1     66538.617637
2     46703.107995
3    146042.611245
4    159326.640454
..             ...
156   92321.143577
157   80021.199570
158   62869.305140
159   81976.495901
160   94393.827261

[161 rows x 1 columns]

In [15]:
y_test

      Price
192   50990
294   72990
168   41490
521  144690
535  129990
..      ...
362  114990
355  126000
436   57990
746  106990
514  110999

[161 rows x 1 columns]

In [16]:
x_test

,brand,processor_brand,processor,gen,ram,ssd,hdd,os,os_bit,gpu,warranty,Touchscreen,msoffice,rating,Number of Ratings,Number of Reviews
192,7,1,2,7,8,0,512,2,0,2,3,0,0,4,10966,1185
294,1,1,2,1,8,512,0,2,0,0,0,0,1,4,76,14
168,3,1,1,0,8,256,1024,2,1,0,0,0,1,5,7,5
521,4,1,3,0,16,1024,0,2,1,3,0,0,1,4,17,4
535,6,1,3,1,16,1024,0,2,1,4,1,0,0,4,14,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,1,1,2,1,8,512,0,2,1,0,0,1,0,3,0,0
355,4,1,2,0,8,512,0,2,1,0,0,1,0,5,2,1
436,3,1,2,1,8,256,1024,2,1,0,0,0,0,4,47,0
746,5,0,9,7,4,512,0,2,1,2,0,0,0,3,0,0
514,5,1,3,1,16,512,0,2,0,0,3,0,0,3,0,0

In [17]:
pd.concat([pred, y_test])

                 0     Price
0     41735.055379       NaN
1     66538.617637       NaN
2     46703.107995       NaN
3    146042.611245       NaN
4    159326.640454       NaN
..             ...       ...
362            NaN  114990.0
355            NaN  126000.0
436            NaN   57990.0
746            NaN  106990.0
514            NaN  110999.0

[322 rows x 2 columns]

In [18]:
import joblib
joblib.dump(lr,"laptop_model.lb")

['laptop_model.lb']